### ISSUE TITLE
Host generated docs on GitHub pages?

### ISSUE THREAD

**Issue by ToucheSir** [CONDUITlab/ccdef#18]
Might be worth setting up an Action to auto-build them as well.

**Comment by ToucheSir** [comment]
cc @prlaird

**Comment by prlaird** [comment]
That's a great idea.. I hadn't really thought of that.. this is more of a draft of the standard than docs per se, but it would be a good idea. I've never setup GitHub pages.. I take it we can have one for the lab and one for each project? 
Can you auto-build using sphinx?

**Comment by ToucheSir** [comment]
Yup, I'll have a look into that!
