### ISSUE TITLE
KHSC channel data not reflected by channel label 

### ISSUE THREAD

**Issue by alexhamiltonRN** [CONDUITlab/ccdef#7]
Some channels vary depending on what is being transduced (meaning channel label is wrong). 
For example, transducer for abd pressure might be plugged into CVP2 channel. 
 
How do we handle this in the mapping table? 

- Do we provide multiple loinc codes for what we expect to find there? 
- Maybe these should be more generic label ("trans1", "trans2") instead of CVP1, CVP2 etc.?

**Comment by prlaird** [comment]
This is a huge problem in almost all these datasets. I think the best thing to do is to educate the bedside nurses to change the monitor when transfusing something other than CVP (eg the monitor can be set to IAP - I think). 
It will be really hard to catch all cases of this mislabeling but I think we could eventually develop a classifier/SQ metric that flags regions where a "CVP" is clearly non-pulsatile. That will be a good next step project!

**Comment by prlaird** [comment]
For the first round of the mapping table I would just "trust" the signal name for now.
